#!/bin/bash
# Skill Queue Hook — Matches prompt against skill index, injects phased queue for multi-skill tasks
# Upgrades skill-first-check.sh with keyword matching + subagent delegation protocol
#
# Hook type: UserPromptSubmit (context injection, non-blocking)
# Dependency: skill-index.txt (generated by build-skill-index.sh)
# https://github.com/MohamedBIqbal/skill-gate

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INDEX_FILE="${SCRIPT_DIR}/skill-index.txt"
SKILLS_DIR="${PROJECT_DIR}/.claude/skills"

INPUT=$(cat)
PROMPT=$(echo "$INPUT" | jq -r '.prompt // empty' 2>/dev/null)

# Bail if jq failed or prompt is empty
if [ -z "$PROMPT" ]; then exit 0; fi

# Skip reminders for simple operations
if echo "$PROMPT" | grep -qiE '^(git |ls |cat |/clear|/help|/compact|/hooks|/commit|hey|hi |hello|thanks|thank you|yes|no|ok|sure|go ahead|yep|nope)'; then
  exit 0
fi

# Skip for very short prompts (likely conversational)
WORD_COUNT=$(echo "$PROMPT" | wc -w | tr -d ' ')
if [ "$WORD_COUNT" -lt 4 ]; then
  exit 0
fi

# Auto-rebuild index if stale (new skills added/removed since last build)
if [ -d "$SKILLS_DIR" ] && [ -f "$INDEX_FILE" ]; then
  CURRENT_COUNT=$(find "$SKILLS_DIR" -name "SKILL.md" -maxdepth 2 | grep -v "skill-first" | wc -l | tr -d ' ')
  INDEX_COUNT=$(wc -l < "$INDEX_FILE" | tr -d ' ')
  # Also check if any SKILL.md is newer than the index
  NEWER=$(find "$SKILLS_DIR" -name "SKILL.md" -maxdepth 2 -newer "$INDEX_FILE" 2>/dev/null | head -1)
  if [ "$CURRENT_COUNT" -ne "$INDEX_COUNT" ] || [ -n "$NEWER" ]; then
    "${SCRIPT_DIR}/build-skill-index.sh" > /dev/null 2>&1 || true
  fi
fi

# Fall back to flat list if index doesn't exist
if [ ! -f "$INDEX_FILE" ]; then
  if [ -d "$SKILLS_DIR" ]; then
    SKILL_LIST=$(find "$SKILLS_DIR" -name "SKILL.md" -maxdepth 2 | while read -r f; do
      basename "$(dirname "$f")"
    done | grep -v "skill-first" | sort | tr '\n' ',' | sed 's/,$//')
    SKILL_COUNT=$(echo "$SKILL_LIST" | tr ',' '\n' | grep -c '.')
    cat <<ENDJSON
{
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": "SKILL-GATE: This project has ${SKILL_COUNT} skills. Before implementing or designing anything, check if any match this task: ${SKILL_LIST}. Invoke matching skills BEFORE using built-in knowledge."
  }
}
ENDJSON
  fi
  exit 0
fi

# --- Keyword matching against skill-index.txt ---

# Tokenize prompt: lowercase, extract words
PROMPT_WORDS=$(echo "$PROMPT" | tr '[:upper:]' '[:lower:]' | tr -cs '[:alpha:]' '\n' | sort -u)

# Match each skill: count keyword overlaps, require 2+ matches
MATCHED_SKILLS=""
while IFS=: read -r skill_name keywords; do
  [ -z "$skill_name" ] && continue
  match_count=0
  for kw in $(echo "$keywords" | tr ',' ' '); do
    if echo "$PROMPT_WORDS" | grep -qw "$kw"; then
      match_count=$((match_count + 1))
    fi
  done
  if [ "$match_count" -ge 2 ]; then
    MATCHED_SKILLS="${MATCHED_SKILLS}${skill_name}:${match_count}\n"
  fi
done < "$INDEX_FILE"

# Count matches (printf avoids echo -e portability issues; tr strips whitespace)
MATCH_COUNT=$(printf '%b' "$MATCHED_SKILLS" | grep -c '.' 2>/dev/null | tr -d '[:space:]')
MATCH_COUNT=${MATCH_COUNT:-0}

# --- 0 matches: inject flat list as reminder ---
if [ "$MATCH_COUNT" -eq 0 ]; then
  SKILL_LIST=$(awk -F: '{print $1}' "$INDEX_FILE" | sort | tr '\n' ',' | sed 's/,$//')
  SKILL_COUNT=$(awk -F: 'NF{c++} END{print c}' "$INDEX_FILE")
  cat <<ENDJSON
{
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": "SKILL-GATE: This project has ${SKILL_COUNT} skills. Before implementing or designing anything, check if any match this task: ${SKILL_LIST}. Invoke matching skills BEFORE using built-in knowledge."
  }
}
ENDJSON
  exit 0
fi

# --- 1 match: use normal Skill tool ---
if [ "$MATCH_COUNT" -eq 1 ]; then
  SKILL_NAME=$(printf '%b' "$MATCHED_SKILLS" | head -1 | cut -d: -f1)
  cat <<ENDJSON
{
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": "SKILL-MATCH: Task matches skill '${SKILL_NAME}'. Invoke it via the Skill tool before implementing."
  }
}
ENDJSON
  exit 0
fi

# --- 2+ matches: build phased queue ---

# Phase assignment — customize this for your project's skill domains.
# Default phases follow a natural workflow: specify → design → domain → implement → quality → ops.
# Skills not listed here default to phase 4 (implement).
# To customize: edit the case statement below or create .claude/hooks/skill-phases.conf
PHASE_CONF="${SCRIPT_DIR}/skill-phases.conf"

assign_phase() {
  # Check external config first
  if [ -f "$PHASE_CONF" ]; then
    local result
    result=$(grep "^$1:" "$PHASE_CONF" 2>/dev/null | cut -d: -f2-3)
    if [ -n "$result" ]; then
      echo "$result"
      return
    fi
  fi
  # Default: everything goes to implement phase
  echo "3:implement"
}

# Sort matched skills into phases
printf '%b' "$MATCHED_SKILLS" | grep '.' | while IFS=: read -r skill_name match_count; do
  phase=$(assign_phase "$skill_name")
  echo "${phase}:${skill_name}"
done | sort -t: -k1,1n > /tmp/skill-queue-$$

# Build queue display
QUEUE_LINES=""
CURRENT_PHASE=""
while IFS=: read -r phase_num phase_name skill_name; do
  phase_label="${phase_num}:${phase_name}"
  if [ "$phase_label" != "$CURRENT_PHASE" ]; then
    CURRENT_PHASE="$phase_label"
    QUEUE_LINES="${QUEUE_LINES}\n- Phase ${phase_num} (${phase_name}): ${skill_name}"
  else
    QUEUE_LINES="${QUEUE_LINES}, ${skill_name}"
  fi
done < /tmp/skill-queue-$$

# Get skill list for display
SKILL_LIST=$(awk -F: '{print $3}' /tmp/skill-queue-$$ | tr '\n' ',' | sed 's/,$//')
rm -f /tmp/skill-queue-$$

# Build the protocol instruction
CONTEXT="SKILL-QUEUE: Task matches ${MATCH_COUNT} skills (${SKILL_LIST}). Use the skill-queue protocol — do NOT load all into main context via Skill tool.\\n\\nQueue:${QUEUE_LINES}\\n\\nProtocol:\\n1. For each skill in queue order, spawn a subagent via Agent tool (model: sonnet).\\n2. Subagent prompt: Read .claude/skills/{name}/SKILL.md, apply its guidance to the task, return a structured summary (decisions, constraints, artifacts).\\n3. Pass accumulated phase summaries to each subsequent subagent as context.\\n4. After all phases, synthesize summaries into your response.\\n5. Do NOT use the Skill tool for queued skills — it loads permanently into main context.\\n6. For single follow-up questions about one skill, the Skill tool is fine."

# Escape for JSON
CONTEXT_JSON=$(printf '%s' "$CONTEXT" | jq -Rs '.')

cat <<ENDJSON
{
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": ${CONTEXT_JSON}
  }
}
ENDJSON
